import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react';
// import { sendWelcomeEmail } from '../emails/account';
import { sendContactForm } from '../lib/api';


const initValues = { name: "", email: "",  };
const initState = { isLoading: false, error: "", values: initValues };


export default function Home() {

  // const [email, setEmail] = useState('');
  // const [name, setName] = useState('');


  const [state, setState] = useState(initState);
  const [touched, setTouched] = useState({});


  const { values, isLoading, error } = state;

  const onBlur = ({ target }) =>
    setTouched((prev) => ({ ...prev, [target.name]: true }));

  const handleChange = ({ target }) =>
    setState((prev) => ({
      ...prev,
      values: {
        ...prev.values,
        [target.name]: target.value,
      },
    }));

  const handleSubmit = async (e) => {
    e.preventDefault();
  //  console.log(email,name)


   setState((prev) => ({
    ...prev,
    isLoading: true,
  }));
  try {
    await sendContactForm(values);
    setTouched({});
    setState(initState);
    toast({
      title: "Message sent.",
      status: "success",
      duration: 2000,
      position: "top",
    });
  } catch (error) {
    setState((prev) => ({
      ...prev,
      isLoading: false,
      error: error.message,
    }));
  }









  // try {
  //   await sendContactForm(email,name );
  // } catch (error) {
  //   console.log("error", error)
  // }


  };


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form onSubmit={handleSubmit}>


         <input type="email" placeholder='email' 
        //  value={email} onChange={e => setEmail(e.target.value)} 
        
        name="email"
          value={values.email}
          onChange={handleChange}
          onBlur={onBlur}

         />
       
      <input type="text" 
     name="name"
      value={values.name}
          onChange={handleChange}
          onBlur={onBlur}
      //  onChange={e => setName(e.target.value)} 

       />
      <button type="submit">Sign Up</button>
    </form>
   
    </div>
  )
}
